const a = {
  login: 'Log in',
  unLogin: 'Not logged in',
  email: 'Email',
  phone: 'Phone',
  jump: 'Jump over',
  giveUp: 'Give up',
  cancel: 'Cancel',
  confirm: 'Confirm',
  finish: 'Carry out',
  search: 'Search',
  loginSuccess: 'Login success',
  loginPwd: 'Login password',
  copySuccess: 'Copy success',
  copy: 'Copy',
  allRead: 'All read',
  noData: 'No Data',
  unbound: 'Not linked',
  bind: 'Linked',
  unSetting: 'Not set',
  logout: 'Sign out',
  hashRateNum: 'Quantity:',
  shareRatio: 'Share ratio:',
  outPutTime: 'Pay out time:',
  day: 'Day',
  countHour: 'Hour',
  countMinute: 'Minute',
  countSecond: 'Second',
  buy: 'Buy',
  updateTime: 'Update time',
  high: 'high',
  low: 'low',
  operationSuccess: 'Operation Success',
  operationFail: 'Operation Fail',
  sendVerifyCode: 'Send verify code',
  boy: 'Male',
  girl: 'Female',
  idCard: 'ID Card',
  driverLicense: 'Driver License',
  passport: 'Passport',
  name: 'Name',
  sex: 'Gender',
  nationality: 'Nationality',
  unChoice: 'Not selected',
  next: 'Next',
  realNameAuth: 'Verified',
  reUpload: 'Re-upload',
  reMake: 'Re-Take',
  confirmCompletion: 'Confirmed',
  secondsReturn: 's return',
  setting: 'Setting',
  version: 'Version',
  cache: 'Cache',
  httpError: 'There was an error in the request, please try again later!',
  refusePermission: 'Permission request denied',
  saveSuccess: 'Save Success',
  saveFail: 'Save Failed',
  well: 'OK',
  viewNow: 'View now',
  hashrate: 'Hash Rate',
  hashrateBuff: 'Hashrate buff',
  additionRatio: 'Addition ratio',
  additionTime: 'Addition time',
  additionDay: 'Addition day',
  closePeriod: 'Lock-up period',
  unitPrice: 'Unit price',
  sellPrice: 'Sell price',
  all: 'All',
  coinHashrate: '{coin} hashrate',
  max: 'max',
  pay: 'pay',
  part: 'part',
  specialDiscount: 'Special discount',
  discount: 'discount',
  limitNum: 'Restricted number of purchases',
  tryAgain: 'Try again',
  noNet: 'The network is lost!',
  expand: 'Full text',
  closeUp: 'Put away',
  powerOff: 'Shut down',
  share: 'Share',
  paste: 'Paste',
  save: 'Save',
  edit: 'Edit',
  to: 'to',
  scan: 'Scan',
  clip: 'Paste',
  present: 'present',
  remain: 'remain',
  selectPlaceholder: 'Please Choose',
  view: 'view',
  type: 'type',
  signInTips: 'Unregistered account will directly register and log in',
  signInPhone: 'Use mobile phone',
  signInEmail: 'Use mailbox',
  signInPhoneNum: 'Cell Phone number',
  signInEmailNum: 'Email',
  signInUserAgreement: 'User agreement',
  signInServiceAgreement: 'MineProfit mining machine sharing service agreement',
  signInRegister: 'Registration means you agree',
  signInSendVerifyCode: 'Send the verification code',
  signInPwd: 'Password login',
  signInVerifyCode: 'Verification code login',
  signInInputVerifyCode: 'Enter confirmation code',
  signInReSendPhoneCode: 'Resend SMS verification code',
  signInReSendEmailCode: 'Resend email verification code',
  signInReGetCode: 'Can be retrieved in seconds',
  countryCodeSelectCountry: 'Choose a country',
  countryCodeSelectArea: 'area',
  inputInviteCodeBind: 'Bind invitation code',
  inputInviteCodeBindSuccess: 'Invitation code binding successfully',
  inputInviteCodeFirstTips: 'Get MineProfit gift package worth $26',
  inputInviteCodeOtherTips: 'Get newcomer gift package',
  drawerInviteFriend: 'invite friends',
  drawerVipCoupon: 'VIP hash rate coupons',
  drawerMessage: 'Station letter',
  drawerAccountAndSecurity: 'Account and security',
  drawerBindInviteCode: 'Bind invitation code',
  drawerSetting: 'Setting',
  drawerCustomerService: 'Online Chat',
  settingLanguage: '语言设置',
  inviteFriendsNumbers: 'Number of Invites',
  inviteFriendsRewards: 'Invitation reward',
  inviteFriendsPerson: 'Person',
  inviteFriendsDetail: 'Detail',
  inviteFriendsMyInviteCode: 'My invitation code',
  inviteFriendsShareOne: 'Share 1',
  inviteFriendsShareBtn: 'Promote via share button',
  inviteFriendsShareFriend: 'Share with friends immediately',
  inviteFriendsShareTwo: 'Share 2',
  inviteFriendsShareZxing: 'Scan or send QR code',
  inviteFriendsSaveZxing: 'Save the QR code',
  inviteFriendsShareThree: 'Share 3',
  inviteFriendsShareLink: 'Share via link',
  inviteFriendsGift: 'Free BTC computing power package',
  inviteFriendsDirectReward: 'Directly invite rewards',
  inviteFriendsIndirectReward: 'Indirect reward',
  inviteFriendsSort: 'Invitation reward sorting',
  inviteFriendsSortAll: 'Reward according to invitation',
  inviteFriendsSortDirect: 'Directly invite rewards',
  inviteFriendsSortIndirect: 'In accordance with the invitation award',
  inviteFriendsTips: '我在MineProfit送你一份价值168元的算力礼包，点击领取[{link}]',
  vipCouponTips: 'Use when buying new hashrate to get extra hashrate',
  vipCouponType: 'Used/Invalid',
  vipCouponTitle: 'VIP hash rate coupons',
  vipCouponTitleOther: 'Used/invalidated hashrate coupons',
  vipCouponDateForever: 'Validity period: permanent',
  vipCouponDate: 'Validity period:',
  vipCouponUse: 'use',
  vipCouponCurrentSelect: 'Current selection',
  vipCouponUseLimit: 'Use limit：new purchse of hashrate >=',
  vipCouponTypeOutputMost: 'Maximum output',
  vipCouponTypeAlmostExpired: 'Expiring soon',
  vipCouponTypeNewCome: 'Newly acquired',
  inStationMessageTitle: 'Station letter',
  inStationMessageDetailTitle: 'Site letter details',
  inStationDialogTips: 'Is it marked as all read?',
  logoutDialogTips: 'Are you sure you want to log out of the current account?',
  accountAndSecurityHead: 'Avatar',
  accountAndSecurityTitle: 'Account and security',
  accountAndSecurityAccount: 'account number',
  accountAndSecurityNickName: 'nickname',
  accountAndSecurityTradePwd: 'transaction password',
  accountAndSecurityRealNameAuth: 'Verified',
  accountAndSecurityGoAuth: 'Go to certification',
  accountAndSecurityAuth: 'Certification',
  accountAndSecurityAuthFail: 'Authentication failed',
  accountAndSecurityAuthSuccess: 'Real-named',
  accountAndSecurityFromAlbum: 'Select from album',
  nickNameTitle: 'Set nickname',
  nickNameHint: 'Please enter your nickname',
  nickNameTips: 'Within 30 characters',
  bindAccountPhoneTips: 'Please enter the phone number you want to bind',
  bindAccountEmailTips: 'Please enter the email address you want to bind',
  bindAccountHint: 'Please enter the one you want to bind',
  bindAccountSecurityVerify: 'safety verification',
  bindAccountWhereSendCode: 'Verification code has been sent to {account} Please check it',
  securityVerifyTips: 'In order to ensure the security of your account, please verify your identity. After successful verification, proceed to the next step',
  noticeCarouselTitle: 'see more',
  noticeDetailPageTitle: 'Announcement Center',
  noticeDetailPageNotice: 'announcement',
  noticeDetailPageFAQ: '常见问答',
  noticeDetailPageViewCount: 'Views',
  noticeDetailPageUnknowTime: 'Time unknown',
  noticeDetailPageFAQSearch: 'Search for the question you want to ask',
  homeBarCoupon: 'VIP hashrate coupons available',
  homeBottomKnowMore: 'Click to learn more',
  homeFiledData: 'Mine data',
  homeMarketData: 'Currency Quotes',
  homeCurrentRate: 'Current hashrate',
  homeYesterdayOutput: "Yesterday's output",
  homeYesterdayOutputValue: "Yesterday's output value",
  homeNoticeMore: 'see more',
  kLineNetStatus: 'network status',
  kLineHashRate: 'The whole network hashrate',
  kLineDifficulty: 'Network Difficulty',
  kLineOutput: 'Daily output',
  kLineOutputValue: 'Daily output value',
  rankTitleTotal: 'Total revenue list',
  rankTitleAngel: 'Angel list',
  rankTitleNew: 'New Purchase List',
  rankPeriod: 'period',
  rankHistory: 'View history',
  rankHistoryTitle: 'Historical ranking',
  rankMine: 'My ranking',
  rankAll: 'All ranking',
  rankNoData: 'No data',
  rankFail: 'Not on the list',
  rankAward: 'Check the reward settings of this issue',
  rankAwardTitle: 'Reward settings for this issue',
  rankRule: 'rule',
  rankRuleTotal: '1.以当期客户所获得的总收益进行排行\r\n2.最终解释权归MineProfit\r\n',
  rankRuleAngel: '1.以当期客户通过推广所获得的直邀奖励进行排行\r\n2.最终解释权归MineProfit\r\n',
  rankRuleNew: '1.以当期客户新购的算力进行排行\r\n2.ETH算力5M=1TBTC算力，以BTC算力为计算标准\r\n3.购买C2C算力的计算量需*50%\r\n4.最终解释权归MineProfit\r\n',
  pwdSettingTitle: 'Setting login password',
  pwdSettingPwdTypeTips: 'The login password is a combination of 6-20 digits and letters',
  pwdSettingEqualTips: 'The new password is inconsistent with the repeated password',
  pwdSettingNewPwd: 'New login password',
  pwdSettingNewPwdHint: 'Please enter a new login password',
  pwdSettingNewPwdAgain: 'confirm login password',
  pwdSettingNewPwdAgainHint: 'Please enter the new login password again',
  tradePwdSettingPwdTypeTips: 'The transaction password is a combination of 6-20 digits and letters',
  tradePwdSettingTitle: 'Set transaction password',
  tradePwdSettingTradePwd: 'transaction password',
  tradePwdSettingTradePwdHint: 'Please enter transaction password',
  tradePwdSettingTradePwdAgain: 'Confirm transaction password',
  tradePwdSettingTradePwdAgainHint: 'Please enter the transaction password again',
  realNameAuthChoiceSex: 'Choose gender',
  realNameAuthChoiceCertificate: 'Select document type',
  realNameAuthRefuseCameraPermission: 'Application for photo permission was rejected',
  realNameAuthRefuseRecordPermission: 'Recording permission application rejected',
  realNameAuthNameInput: 'Please enter the name of the certificate',
  realNameAuthCertificateType: 'type of certificate',
  realNameAuthCertificateNum: 'ID number',
  realNameAuthCertificateNumInput: 'Please enter the ID number',
  realNameAuthDateOfBirth: 'date of birth',
  realNameAuthAddress: 'Current address',
  realNameAuthAddressInput: 'Please enter your current residence',
  realNameAuthIDCardFront: 'Upload the front of the ID card',
  realNameAuthIDCardBack: 'Upload the back of the ID card',
  realNameAuthPassportCover: 'Upload passport cover',
  realNameAuthPassportContent: 'Upload your passport personal information page',
  realNameAuthUpDriver: "Upload driver's license",
  realNameAuthUpCertificatePhoto: 'Upload ID photo',
  authVideoNoCameraAvailable: 'No camera available',
  authVideoTitle: 'Video certification',
  authVideoRemainTime: '{RemainTime} seconds remaining',
  authVideoTips: 'Hold your ID and aim at the lens\r\nAfter clicking start, say the following certification numbers within 10 seconds',
  authVideoStartRecordTips: 's start recording',
  authImageUsePhoto: 'Use photos',
  authImageTips: 'Please confirm that the text of the picture is clear and the certificate is complete',
  authFinishTips: 'The real-name authentication information you submitted has been received please wait patiently',
  settingClearCacheTips: 'Are you sure you want to clear the cache?',
  settingUpdateTips: 'Are you sure you want to update the version?',
  guideOneTipsOne: 'The hashrate ecosystem helps you make extraordinary profits',
  guideOneTipsTwo: 'The hashrate ecosystem constructed by selling market and pledge markets\r\nenables you to realize flexible asset allocation and obtain optimal returns.',
  guideTwoTipsOne: 'The specialized data improve your profitability',
  guideTwoTipsTwo: 'Professional, instant and easy-to-understand hash rate data information\r\nhelps you understand the market in real time，Market dynamics and grasp market opportunities.',
  guideThreeTipsOne: 'One-click operation to help you get started quickly',
  guideThreeTipsTwo: 'Convenient registration, recharge, and purchase process,\r\nso that you can get hashrate in seconds.\r\nHave mining income immediately.',
  guideStart: 'Start my profitability',
  ratioDialogRatio: 'Allocation ratio',
  ratioDialogDesc: 'After deducting the electricity cost per unit of computing power, the customer’s distribution',
  ratioDialogRatioDefault: 'Default allocation ratio',
  ratioDialogOutputAddition: 'Output bonus',
  hashRateCouponDialogGetCoupon: 'Get VIP hashrate coupons',
  hashRateCouponDialogContent: '· Has been placed in "Account-VIP Hash rate Coupon" ·',
  hashRateBuffDialogDesc: 'The hashrate output bonus obtained through the activity',
  pledgeDialogOriginal: 'Original pledge hashrate',
  pledgeDialogGet: 'Stake to obtain hashrate',
  newBuyDialogDesc: '*Purchase current hashrate and enjoy output bonus after excavation.',
  renewalDialogTitleOne: 'Bonus renewal days',
  renewalDialogRenewableHashrate: 'Renewable hashrate',
  renewalDialogDesOne: '1. It can extend the validity period of the bonus calculation power of the same series.',
  renewalDialogTitleTwo: '2. The amount of new hashrate purchased by the same amount can be extended, and the maximum amount does not exceed the renewable hashrate:',
  renewalDialogDesTwo: '100M hashrate can be renewed, if you purchase a new hashrate of 50M, you can renew 50M Renewable\r\n100M hashrate, purchase new 200M computing power, then renew 100M"',
  renewalDialogTitleThree: 'Renewable 100M hashrate, purchase new 200M hashrate, then renew 100M"',
  verifyDialogTips: 'Real-name authentication',
  verifyDialogContent: 'To ensure your account compliance and transaction security, you need to supplement the following information',
  verifyTypeDialogTitle: 'Real-name authentication information submitted by you',
  verifyTypeDialogFailed: 'not approved',
  verifyTypeDialogTryAgain: 'Please try again',
  verifyTypeDialogTips: 'The real-name authentication information you submitted has been received please wait patiently',
  payWaitPay: 'To be paid',
  paySelectWallet: 'Choose a payment wallet',
  payNotEnough: 'Insufficient wallet balance',
  payImmediateRecharge: 'Deposit now',
  payImmediatePay: 'Immediate payment',
  payCheckAgremmentHint: 'Please check the investment agreement first',
  payPwdEmptyHint: 'Transaction password cannot be empty',
  payPwdFormatHint: 'Incorrect transaction password format',
  payInputPwd: 'Please enter transaction password',
  payForgetPwd: 'Forgot trading password?',
  payBuySuccess: 'Successfully bought!',
  payReturnMineHashrate: "s return to 'My Hashrate'",
  payRepaySuccess: 'Successful repayment!',
  payRedeemSuccess: 'Redemption is successful!',
  payRetrunHashratePledge: "s return to 'Pledge'",
  payInvestSuccess: 'Successful investment!',
  payReturnMineInvest: "s return to 'My Investment'",
  payTypeHashrate: 'Buy hashrate',
  payTypeRedeem: 'Early redemption',
  payTypeRepay: 'Repay immediately',
  payTypeInvest: 'Pledged investment',
  marketSoldOut: 'Sold out',
  marketImmediateBuy: 'Buy now',
  marketStartMineTime: 'Excavation time',
  marketCurrentOutput: 'Current daily output',
  marketDistributeRatio: 'Allocation ratio',
  marketNetOutput: 'Daily net output',
  marketNetOutputDes: 'After deducting the daily electricity bill based on the daily output\r\nCalculated according to the contract distribution ratio',
  marketAnnualRate: 'Estimated annualization',
  marketAnnualRateDes: 'Calculated based on the current currency price, for reference only',
  marketRemainHashrate: 'Purchasable hashrate',
  marketDetailDescription: 'detail intruduction',
  marketReleaseTime: 'release time',
  marketEverydayNetOutput: 'Daily net output',
  marketItemRemainAmount: 'Available for purchase',
  marketPreOrderFail: 'Pre-order failed',
  marketConfirmSettle: 'Confirm settlement',
  marketFieldHintMax: 'Max.',
  marketHashTotalPrice: 'Total price of hashrate',
  marketHashDetail: 'Product details',
  marketRateChangeHint: 'Dear customer, due to exchange rate fluctuations\r\nYour payment amount has changed',
  marketOriginPayAmount: 'Original amount to be paid',
  marketCurrentPayAmount: 'Amount currently to be paid',
  marketPayChainTypeNotEnough: '*The current {paymentChainType} amount is insufficient',
  marketOfficialMarket: 'Official market',
  marketC2CMarket: 'C2C market',
  markeMyOrde: 'My Order',
  marketNewBuyBuff: 'New purchase bonus',
  marketRenewBuff: 'Repurchase renewal',
  marketPartHash: 'Per share',
  marketConvertUnitPrice: 'Converted unit price',
  marketClosePeriod: 'lock-up period',
  marketClosePeriodDes: 'C2C transactions cannot be performed during the lock-up period',
  marketNewUserExclusive: 'Exclusive',
  marketRemainTime: 'Remaining',
  marketExpect: 'Stay tuned',
  marketOnlineTime: 'On sale',
  marketNewUserDeadLine: 'Cut off',
  marketPartPrice: 'Price per copy',
  refreshLoad: 'Pull up loading',
  refreshLoadReady: 'Release and load immediately',
  refreshLoading: 'Loading...',
  refreshLoaded: 'download finished',
  refreshNoMore: 'No more',
  refreshFailed: 'Failed to load',
  refreshPullRefresh: 'Pull down to refresh',
  refreshPullReady: 'Refresh immediately after release',
  refreshPulling: 'Refreshing...',
  refreshPulled: 'Refresh complete',
  refreshPullFailed: 'Refresh failed',
  agreementViewTitle: 'MineProfit Investment Invitation Terms',
  agreementViewAgree: 'I have agreed',
  tabHome: 'Home page',
  tabRank: 'ranking',
  tabInfo: '资讯',
  tabMine: 'mine',
  quitConfirm: '再次点击退出MineProfit',
  marketBuyPart: 'Number of copies purchased',
  marketTotalHashrate: 'Total hashrate',
  marketExclusiveDiscount: 'Exclusive offer',
  marketDiscountNewBuyDes: 'After the newly purchased hashrate starts to be produced, {buffDays} will produce {buffRate} daily for the day',
  marketDiscountRenewLeft: 'Renewal hashrate',
  marketDiscountRenewRight: ', The validity period is renewed for {buffDays} days',
  marketReSelectCouponHint: 'Please re-select hashrate coupons',
  marketSelectCouponHint: 'please choose',
  marketOrderBuyTime: 'Purchase time',
  marketOrderSource: 'Source of purchase',
  marketOrderOrderAmount: 'order amount',
  marketOrderPayAmount: 'Payment amount',
  webDefaultTitle: 'Details',
  webShareLink: 'Share link',
  mineTitleWallet: 'wallet',
  mineTitleHashrate: 'Computing power',
  mineTitleInvest: 'investment',
  commonMinNum: 'Minimum input {num}',
  commonMaxNum: 'Maximum input {num}',
  commonTips: 'The maximum value cannot be less than the minimum value',
  investResonRisk: 'Risk control settlement',
  investResonRedeem: 'redemption',
  investResonRepay: 'Repayment due',
  investResonBreakContract: 'Default settlement',
  investResonOutputLow: 'Output cannot pay interest',
  investItemPrincipal: 'Subscription principal',
  investItemDuration: 'Investment period',
  investItemAnnualRate: 'Annualized rate of return',
  investItemSettledProfit: 'Settled income',
  investItemReson: 'Reason for settlement',
  investItemTime: 'Settlement time',
  investItemTitle: 's borrowing',
  investTypeProfiting: 'In income ···',
  investTypeSettled: 'Settled _',
  investNoReason: 'Unknown reason for settlement',
  infoNews: 'News',
  infoArticle: 'Article',
  infoTop: 'Top',
  infoUnknowTime: 'Time unknown',
  infoViewCount: 'Views',
  infoShareTitle: 'Get hashrate immediately',
  infoScan: 'Scan code to download MineProfit',
  typeAll: 'All',
  typeInRevenue: 'Income',
  typeSettled: 'Settled',
  typeNormal: 'Ordinary',
  typeClose: 'Lock-up',
  typePledge: 'Pledge',
  typeTransfer: 'transfer',
  typeShutDown: 'Shut down',
  typeNew: 'Newest',
  typePassTime: 'Expiring soon',
  typeUsed: 'Used',
  typeInvalid: 'Invalidation',
  walletPasteEmpty: 'The pasteboard has no content to paste',
  walletPasswordEmpty: 'Transaction password cannot be empty',
  walletPasswordFormatWrong: 'Incorrect transaction password format',
  walletAdd: 'Add',
  walletCarryAddress: 'Withdrawal address',
  walletYourCarryAddress: 'Your withdrawal address',
  walletScan: 'Scan QR code',
  walletInputPassword: 'Please enter transaction password',
  walletPleaseLogin: 'please log in first',
  walletForgetDealPassword: 'Forgot trading password?',
  walletAddressWrong: 'The current address format is wrong, please change',
  walletAddAddress: 'Add address',
  walletAddressName: 'Address name',
  walletChainName: 'Chain name',
  walletChainType: 'Chain type',
  walletInputAddressName: 'Please enter your address name',
  walletSetAddressName: 'Set address name',
  walletCantEmpty: 'Within 20 characters, cannot be empty',
  walletConfirmDeleteAddress: 'Are you sure to delete this address?',
  walletDeleteSuccess: 'successfully deleted',
  walletNoPasteContent: 'No content to paste',
  walletModifyAddress: 'Change address',
  walletDeleteCoinAddress: 'Delete the withdrawal address',
  walletSelectTime: 'selection period',
  walletInWeek: 'within a week',
  walletInMonth: 'Within a month',
  walletInThreeMonth: 'Within three months',
  walletInHalfYear: 'Within half a year',
  walletSelectCoinType: 'Choose currency',
  walletCharge: 'Recharge',
  walletAccount: 'Account',
  walletQRCodeEmpty: 'QR code is empty',
  walletSaveQRCode: 'Save the QR code',
  walletCopyAddressSuccess: 'Address copied successfully',
  walletAddressEmpty: 'Address is empty',
  walletChargeAddress: 'Deposit address',
  walletDetail: 'Wallet details',
  walletAllTypesAll: 'All types',
  walletAllTypesCharge: 'Recharge',
  walletAllTypesCarry: 'Withdraw',
  walletAllTypesBuyHashrate: 'Purchase hashrate',
  walletAllTypesSaleHashrate: 'Sell hashrate',
  walletAllTypesRedeem: 'Pledge redemption',
  walletAllTypesRepay: 'Pledge repayment',
  walletAllTypesInvestPledge: 'Investment pledge',
  walletAllTypesInvestEarning: 'Investment income',
  walletAllTypesInvestAccounts: 'Investment settlement',
  walletAllTypesMining: 'Mining output',
  walletAllTypesAward: 'Promotion reward',
  walletAllCoins: 'All currencies',
  walletStatusAll: 'All status',
  walletStatusOngoing: 'Processing',
  walletStatusFailure: 'Failure',
  walletStatusSuccess: 'Success',
  walletAsset: 'Assets',
  detail: 'Detail',
  walletAssetTotal: 'Wallet asset conversion',
  typeCanceled: 'Cancelled',
  withDrawBalanceTips: 'Balance {balance}',
  withDrawClipboardNoData: 'The pasteboard has no content to paste',
  withDrawTitle: 'Withdraw',
  withDrawSuccess: 'Withdraw successfully',
  withDrawSelectCoin: 'Choose currency',
  withDrawAccount: '{coin} account',
  withDrawAccountBalance: 'Balance {balance}{coin}',
  withDrawChainName: 'Chain name',
  withDrawAddressHint: 'Your withdrawal address',
  withDrawAddress: 'Withdrawal address',
  withDrawMinNum: 'Minimum withdrawal amount: {num}',
  withDrawFee: 'Handling fee',
  withDrawReceivedNum: 'Arrival quantity',
  withDrawNullAddressTips: 'Withdrawal address cannot be empty',
  withDrawErrorAddressTips: 'The current address format is wrong, please change',
  withDrawTips: 'In order to ensure the safety of fund withdrawal, manual review may be required according to the security policy. please wait patiently.',
  withDrawNum: 'Number of withdrawals',
  hashratePledgeSuccess: 'The pledge is successful!',
  hashrateJumpSahre: "s jump to 'Share'",
  hashratePublishSuccess: 'Successfully released!',
  hashrateJumpTransfer: "s jump to 'Transfer'",
  hashratePledgeConfirmHint: 'After confirmation, the quality must be completed within 30 minutes.\r\nStake the subscription, it will be cancelled automatically if it is not completed',
  hashrateOperationPledge: 'Pledge hashrate',
  hashrateOperationTransfer: 'Transfer hashrate',
  hashratePledgeAllNotEnough: 'Too little remaining hashrate',
  hashratePledgeSameNotEnough: 'Insufficient amount of computing power in the same series',
  hashrateYesterdayNetOutput: 'Net output yesterday',
  hashrateTotalHash: 'Total hashrate',
  hashrateAllNetOutput: 'Cumulative net output',
  hashrateVIPHash: 'VIP hashrate',
  hashrateTodayNetOutputPre: "Today's net output (pre)",
  hashrateShutDownHashrate: 'Shutdown hashrate',
  hashrateShutDownTime: 'Shutdown time',
  transferShare: 'Share with friends',
  transferStatusTransfering: 'Transferring ···',
  transferStatusConfirming: 'Cancel confirming ···',
  transferStatusDone: 'Completed _',
  transferItemAmount: 'Transfer computing power',
  transferItemPrice: 'Transfer price',
  transferItemFee: 'Transfer fee',
  transferItemNetMoney: 'Net transfer amount',
  transferCancelHint: 'Hashrate will be returned\r\nReturn period T+1',
  transferContinue: 'Continue to transfer',
  transferC2C: 'C2C transfer',
  transferConfirmHint: 'Hashrate is now producing bonuses\r\nConfirming the transfer will lose the output bonus.',
  transferWontOutput: 'The computing power in the transfer cannot be produced.',
  transferGetPrice: 'Unit price',
  transferRemainAmount: 'Transferable hashrate',
  pledgeRemainCount: '今日还能进行质押取消操作{pledgeCount}次',
  pledgeInvestHint: 'After confirmation, the pledge subscription needs to be completed within 30 minutes, and it will be automatically cancelled if it is not completed.',
  pledgePageTitle: 'Hashrate pledge',
  pledgeHelp: 'Pledge support',
  pledgeSelectDuration: 'Select the pledge period',
  pledgeTotalHashrate: 'Total pledged hashrate',
  pledgeDuration: 'Pledge period',
  pledgeGetHashrate: 'Stake to obtain hashrate',
  pledgeSellPrice: 'Subscription price',
  pledgeAnnualRate: 'APR',
  pledgeCanPledgePart: 'The number of shares that can be pledged',
  pledgeCanPledgePartDes: 'The minimum hashrate that can be pledged is 1 share',
  pledgeCanPledgeAmount: 'Pledgeable hashrate',
  pledgeDeadlineCountDown: 'Countdown to due',
  pledgeRepayPrincipal: 'Principal to be repaid',
  pledgeRepayExplain: '*After the repayment is completed, the pledged computing power will be returned in full at the time of settlement',
  pledgeRedeemPrincipal: 'Principal repayable',
  pledgeRedeemPrincipaled: 'Repaid principal',
  pledgeRedeemInterest: 'Penalty interest to be paid',
  pledgeRedeemTotalMoney: 'Total',
  pledgeImmediateRedeem: 'Redeem immediately',
  pledgeStatusWaitBuy: 'Pending subscription',
  pledgeStatusPledging: 'Pledging',
  pledgeStatusWaitConfirm: 'Settlement to be confirmed',
  pledgeStatusSettled: 'Settled',
  pledgeStatusRepayed: 'Repaid',
  pledgeAgreementTitle: 'MineProfit Tripartite Pledge Agreement',
  pledgeRepayTips: 'Operable within 7 days before the pledge expires',
  pledgeGetDataError: 'Failed to get data, please try again',
  pledgeCancelTips: 'Confirm to cancel the pledge?',
  pledgeCanGet: 'Staking available computing power',
  pledgeDate: 'Pledge period',
  pledgeYearIncome: 'Subscription APR',
  pledgeSubscribePrice: 'Subscription price',
  pledgeSubscribeTips: 'After unsubscribed will be automatically',
  pledgeCancel: 'Cancel pledge',
  pledgeYesterdayOutput: "Yesterday's distribution output",
  pledgeDailyInterest: 'Daily interest',
  pledgeDailyInterestToInvestor: 'Daily interest to be paid to investors',
  pledgeDailyInterestToInvestorTips: 'The actual net output after deducting interest\r\nEarned income',
  pledgeTypeDeductionHashrate: 'Deduction power (to be confirmed)',
  pledgeTypeReturnHashrate: 'Return computing power (to be confirmed)',
  pledgeAllInterest: 'Cumulative interest cost',
  pledgeAllOutput: 'Cumulative net output',
  pledgeTotalSettlementPrice: 'Total settlement price',
  pledgeDeductionHashrate: 'Deductible computing power',
  pledgePenaltyInterestPaid: 'Penalty interest paid',
  pledgeReturnHashrate: 'Return hashrate',
  shareBorrow: '通过MineProfit向你借款',
  shareBorrowAmount: 'Loan amount',
  shareInvestPeriod: 'Investment cycle',
  shareAnnualYield: 'Annualized rate of return',
  shareInvestNow: 'Invest now',
  shareFailure: 'expired',
  shareRestInvestTime: 'Remaining investment time',
  shareTransfer: 'Share with you a hashrate transfer subject',
  shareTransferPrice: 'Transfer price',
  shareGuarantee: '*该投资由MineProfit提供风险保障',
  shareOutdate: 'Expired',
  shareScanDetail: 'Scan the QR code to view details',
  shareCopyPledgeLinkDes: '我正在通过MineProfit向您借款，点击查看[{link}]',
  sharePledgeToFriend: 'Share the pledge subject to friends',
  shareHashWay1: 'Share 1',
  shareHashFromButton: 'Promote via share button',
  shareHashImmediate: 'Share with friends immediately',
  shareHashWay2: 'Share 2',
  shareHashFromQRCode: 'Scan or send promotion QR code',
  shareHashSaveQRCode: 'Save the QR code',
  shareHashWay3: 'Share 3',
  shareHashFromLink: 'Share via link',
  shareCopyTransferLinkDes: '我在MineProfit发布了一份算力转让标的，点击查看[{link}]',
  shareTransferToFriend: 'Share the transfer target with friends',
  shareTransferQRView1: '通过MineProfit',
  shareTransferQRView2: 'Share with you a hashrate transfer subject',
  shareTransferQRView3: 'Scan the QR code to view details',
  publishTime: '发布时间',
  defaultLang: '默认',
  selectLanguage: '选择语言',
  settingNoUpdateTips: '暂无可用更新',
  marketNoGoodsAvailable: '暂无可购买产品',
  marketOrderHashrateNum: '算力数量',
  walletPersonChargeAddress: '{name}的{chainType}充币地址',
  hashrateShutDownReasonOne: '发放错误',
  hashrateShutDownReasonTwo: '违规获得',
  hashrateShutDownReasonThree: '其他原因',
  hashrateShutDownReasonFour: '临时算力到期',
  hashrateShutDownReasonFive: '算力价值过低产出不能支付成本',
  hashrateCancelTransfer: '取消转让',
  hashrateOpen: '算力开机',
  hashrateShutDownPrice: '关机币价',
  hashrateShutDownPriceTips: '当“币价”<=“关机币价”时\r\n产出将无法支付电费\r\n算力将自动关机',
  hashrateCurrentPrice: '当前币价',
  hashrateCurrentPriceTips: '当前币价≥(关机币价*1.05)时\r\n关机算力可开机',
  hashrateCanOpen: '可开机算力',
  hashrateCanOpenTips: '{hashtype}算力最低开机量:{num}{unit}',
  hashrateOpenPrice: '开机维护费',
  hashrateOpenPriceTips: '开机需要付出的人力维护\r\n成本=开机算力*{rate}%',
  hashrateNumOpened: '开机后算力',
  hashrateTime: '开挖时间',
  hashrateOpenTips: '*当币价低于关机币价时，矿机将自动关机，请注意风险。',
  hashrateConfirmOpen: '确认开机',
  hashrateCanNotOpen: '无法开机',
  hashrateOpenSuccess: '开机成功',
  hashrateOpenSuccessTips: 'S之后 返回“我的-算力-关机”',
  hashrateOpening: '开机中 ···'
};
